const routesArray = [
    {
      route:"/squareone",
      instagramUrl:"https://www.instagram.com/squareonecafe/"
    },
    {
      route:"/kfc",
      instagramUrl:"https://www.instagram.com/kfcrepdom/"
    },
    {
      route:"/fridays",
      instagramUrl:"https://www.instagram.com/fridaysrd"
    },
    {
      route:"/tacobell",
      instagramUrl:"https://www.instagram.com/tacobellrd"
    },
    {
      route:"/pizzarelli",
      instagramUrl:"https://www.instagram.com/pizzarellido"
    },
    {
      route:"/subway",
      instagramUrl:"https://www.instagram.com/subwayrepublicadominicana"
    },
    {
      route:"/mcdonalds",
      instagramUrl:"https://www.instagram.com/mcdonaldsrd"
    },
    {
      route:"/papajohns",
      instagramUrl:"https://www.instagram.com/papajohnsrd"
    },
    {
      route:"/lamarkesina",
      instagramUrl:"https://www.instagram.com/lamarkesina"
    },
    {
      route:"/loopfriends",
      instagramUrl:"https://www.instagram.com/looprd"
    },
    {
      route:"/dontato",
      instagramUrl:"https://www.instagram.com/dontatord"
    },
    {
      route:"/norisushi",
      instagramUrl:"https://www.instagram.com/norisushisti"
    },
    {
      route:"/quiznos",
      instagramUrl:"https://www.instagram.com/quiznos_rd"
    },
    {
      route:"/dogos",
      instagramUrl:"https://www.instagram.com/dogosuf"
    },
    {
      route:"/artepizza",
      instagramUrl:"https://www.instagram.com/artepizzard"
    },
    {
      route:"/jadeteriyaki",
      instagramUrl:"https://www.instagram.com/jadeteriyakird"
    },
    {
      route:"/pizzahut",
      instagramUrl:"https://www.instagram.com/pizzahutrd"
    },
    {
      route:"/puchosmofongo",
      instagramUrl:"https://www.instagram.com/puchosmofongo"
    },
    {
      route:"/cositarica",
      instagramUrl:"https://www.instagram.com/cositaricadr"
    },
]


module.exports = {routesArray};