const routesArrayRD = [
    {
      route:"/rd/squareone",
      instagramUrl:"https://www.instagram.com/squareonecafe/"
    },
    {
      route:"/rd/kfc",
      instagramUrl:"https://www.instagram.com/kfcrepdom/"
    },
    {
      route:"/rd/fridays",
      instagramUrl:"https://www.instagram.com/fridaysrd"
    },
    {
      route:"/rd/tacobell",
      instagramUrl:"https://www.instagram.com/tacobellrd"
    },
    {
      route:"/rd/pizzarelli",
      instagramUrl:"https://www.instagram.com/pizzarellido"
    },
    {
      route:"/rd/subway",
      instagramUrl:"https://www.instagram.com/subwayrepublicadominicana"
    },
    {
      route:"/rd/mcdonalds",
      instagramUrl:"https://www.instagram.com/mcdonaldsrd"
    },
    {
      route:"/rd/papajohns",
      instagramUrl:"https://www.instagram.com/papajohnsrd"
    },
    {
      route:"/rd/lamarkesina",
      instagramUrl:"https://www.instagram.com/lamarkesina"
    },
    {
      route:"/rd/loopfriends",
      instagramUrl:"https://www.instagram.com/looprd"
    },
    {
      route:"/rd/dontato",
      instagramUrl:"https://www.instagram.com/dontatord"
    },
    {
      route:"/rd/norisushi",
      instagramUrl:"https://www.instagram.com/norisushisti"
    },
    {
      route:"/rd/quiznos",
      instagramUrl:"https://www.instagram.com/quiznos_rd"
    },
    {
      route:"/rd/dogos",
      instagramUrl:"https://www.instagram.com/dogosuf"
    },
    {
      route:"/rd/artepizza",
      instagramUrl:"https://www.instagram.com/artepizzard"
    },
    {
      route:"/rd/jadeteriyaki",
      instagramUrl:"https://www.instagram.com/jadeteriyakird"
    },
    {
      route:"/rd/pizzahut",
      instagramUrl:"https://www.instagram.com/pizzahutrd"
    },
    {
      route:"/rd/puchosmofongo",
      instagramUrl:"https://www.instagram.com/puchosmofongo"
    },
    {
      route:"/rd/cositarica",
      instagramUrl:"https://www.instagram.com/cositaricadr"
    },
    {
      route:"/rd/tuquipe",
      instagramUrl:"https://www.instagram.com/tuquipe"
    },
    {
      route:"/rd/lacar",
      instagramUrl:"https://www.instagram.com/lacar"
    },
    {
      route:"/rd/dominos",
      instagramUrl:"https://www.instagram.com/dominosrd"
    },
    {
      route:"/rd/dominos",
      instagramUrl:"https://www.instagram.com/dominosrd"
    },
    {
      route:"/rd/nypizza",
      instagramUrl:"https://www.instagram.com/212nypizza"
    },
    {
      route:"/rd/nypizza",
      instagramUrl:"https://www.instagram.com/212nypizza"
    },
    {
      route:"/rd/burgerking",
      instagramUrl:"https://www.instagram.com/burgerkingrd"
    },
    {
      route:"/rd/burgerking",
      instagramUrl:"https://www.instagram.com/burgerkingrd"
    },
    {
      route:"/rd/victorina",
      instagramUrl:"https://www.instagram.com/p_victorina"
    },
    {
      route:"/rd/portobellorestaurant",
      instagramUrl:"https://www.instagram.com/portobello_restaurant"
    },
    {
      route:"/rd/chefpepper",
      instagramUrl:"https://www.instagram.com/chefpepperrd"
    },
    {
      route:"/rd/pizzahouse",
      instagramUrl:"https://www.instagram.com/thepizzahousedom"
    },
    {
      route:"/rd/mrgrilled",
      instagramUrl:"https://www.instagram.com/mrgrilled"
    },
    {
      route:"/rd/restaurantdorado",
      instagramUrl:"https://www.instagram.com/restaurantdorado"
    },

]
/*
*/
module.exports = {routesArrayRD};